- hosts: localhost
  connection: local
  tasks:
    - name: "Shell step:'cat playbook.yml'"
      shell: cat playbook.yml
      register: result
    - name: "Registering custom fact"
      set_fact: from_yaml="{{ result.stdout | from_yaml }}"
    - name: "Output of result.stdout"
      debug: var=result.stdout
    - name: "Output of the custom fact"
      debug: var=from_yaml
